WITH MEDIA_NACIONAL AS (
    SELECT 
        AVG(NOTA_FINAL) AS MEDIA
    FROM (
        SELECT 
            RR.NU_INSCRICAO,
            ((RR.NU_NOTA_REDACAO + RP.SOMA_NOTAS) / 5) AS NOTA_FINAL
        FROM ENEM.RESULTADO_REDACAO RR
        INNER JOIN (
            SELECT 
                NU_INSCRICAO,
                SUM(NU_NOTA) AS SOMA_NOTAS
            FROM ENEM.RESULTADO_PROVA
            GROUP BY NU_INSCRICAO
        ) RP
            ON RR.NU_INSCRICAO = RP.NU_INSCRICAO
    ) TABELA_NOTAS
)

SELECT 
    UF.NO_UF,
    REG.NO_REGIAO,

    -- Média dos participantes da UF
    ROUND(AVG(TABELA_NOTA_FINAL.NOTA_FINAL), 2) AS NOTA_MEDIA,

    -- Média de todos os participantes do Brasil
    ROUND(MEDIA_NACIONAL.MEDIA, 2) AS NOTA_MEDIA_NACIONAL,

    -- Diferença entre a média da UF e a média nacional
    ROUND(
        AVG(TABELA_NOTA_FINAL.NOTA_FINAL) - MEDIA_NACIONAL.MEDIA,
        2
    ) AS DIFERENCA

FROM (
    SELECT 
        RR.NU_INSCRICAO,
        ((RR.NU_NOTA_REDACAO + RP.SOMA_NOTAS) / 5) AS NOTA_FINAL
    FROM ENEM.RESULTADO_REDACAO RR
    INNER JOIN (
        SELECT 
            NU_INSCRICAO,
            SUM(NU_NOTA) AS SOMA_NOTAS
        FROM ENEM.RESULTADO_PROVA
        GROUP BY NU_INSCRICAO
    ) RP
        ON RR.NU_INSCRICAO = RP.NU_INSCRICAO
) TABELA_NOTA_FINAL

INNER JOIN ENEM.PARTICIPANTE PRTCP
    ON TABELA_NOTA_FINAL.NU_INSCRICAO = PRTCP.NU_INSCRICAO

INNER JOIN ENEM.MUNICIPIO MUN
    ON PRTCP.CO_MUNICIPIO_PROVA = MUN.CO_MUNICIPIO

INNER JOIN ENEM.REGIAO_GEOGRAFICA_IMEDIATA REG_IMED
    ON MUN.CO_RG_IMED = REG_IMED.CO_RG_IMED

INNER JOIN ENEM.REGIAO_GEOGRAFICA_INTERMEDIARIA REG_INTERMED
    ON REG_IMED.CO_RG_INTERMED = REG_INTERMED.CO_RG_INTERMED

INNER JOIN ENEM.UNIDADE_FEDERATIVA UF
    ON REG_INTERMED.CO_UF = UF.CO_UF

INNER JOIN ENEM.REGIAO REG
    ON UF.CO_REGIAO = REG.CO_REGIAO

-- A CTE possui apenas uma linha, então o CROSS JOIN
-- disponibiliza a média nacional para todas as UFs
CROSS JOIN MEDIA_NACIONAL

GROUP BY 
    UF.CO_UF,
    UF.NO_UF,
    REG.NO_REGIAO,
    MEDIA_NACIONAL.MEDIA

ORDER BY 
    NOTA_MEDIA DESC;

